---
  parserOptions:
    ecmaVersion: 6
  env:
    browser: true
    jquery: true
  extends: eslint:recommended
  rules:
    no-console: off
    no-unused-vars:
     - error
     - vars: local
       args: none
    no-empty: off
    no-shadow: error
    no-mixed-spaces-and-tabs: [error, smart-tabs]
    id-length: [error, exceptions: [i, j, e, x, y]]

    indent: [error, tab]
    semi: error
    brace-style: [error, 1tbs, allowSingleLine: true]
    linebreak-style: [error, unix]
    semi-spacing: error
    comma-spacing: error
    space-infix-ops: error
    space-before-function-paren: [error, never]
    space-before-blocks: error
    keyword-spacing:
      - error
      - before: true
        after: true
  globals:
    require: true
    unsafeWindow: true

    XKit: true
    XBridge: true
    Tumblr: true
    add_tag: true

    storage_max: true
    storage_used: true
    framework_version: true
    getBridgeError: true

    GM_flushStorage: true
    GM_deleteAllValues: true
    GM_getValue: true
    GM_deleteValue: true
    GM_setValue: true
    GM_log: true
    GM_openInTab: true
    GM_listValues: true
    GM_xmlhttpRequest: true
